eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      #      Same port as in discovery server properties
      defaultZone: http://localhost:8761/eureka

server:
  port: 8070
spring:
  application:
    name: schools #the name that'll be shown on the eureka interface

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/micro_services_db
    username: postgres
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  config:
    students-url: http://localhost:8222/api/v1/students
management:
  tracing:
    sampling:
      probability: 1.0
