spring:
  config:
#    Import an external configuration, optional indicates that the import is optional
#    and if the configuration server is not available, the application will still start
#    using its local configuration
    import: optional:configserver:http://localhost:8888
  application:
    name: discovery